////////////////////////////////////////////////
// Generated by SmartState C++ Code Generator //
//                 DO NOT EDIT				  //
////////////////////////////////////////////////

#ifndef Sender_SS_H
#define Sender_SS_H

#include <ss_api.hxx>

/*Context*/
class SenderY;

namespace Sender_SS
{
	using namespace smartstate;
	//State Mgr
	class SenderSS : public StateMgr
	{
		public:
			SenderSS(SenderY* ctx, bool startMachine=true);

			SenderY& getCtx() const;

		private:
			SenderY* myCtx;
	};

	//Base State
	class SenderBaseState : public BaseState
	{
		protected:
			SenderBaseState(){};
			SenderBaseState(const string& name, BaseState* parent, SenderSS* mgr);

		protected:
			SenderSS* getMgr(){return static_cast<SenderSS*>(myMgr);}
	};

	//States
	//------------------------------------------------------------------------
	class Sender_TopLevel_SenderSS : public virtual SenderBaseState
	{
			typedef SenderBaseState super;

		public:
			Sender_TopLevel_SenderSS(){};
			Sender_TopLevel_SenderSS(const string& name, BaseState* parent, SenderSS* mgr);

			virtual void onMessage(const Mesg& mesg);

			virtual void onEntry();
			virtual void onExit();

		//Transitions

		private:
			void onSERMessage(const Mesg& mesg);
	};

	class NON_CAN_Sender_TopLevel : public virtual Sender_TopLevel_SenderSS
	{
			typedef Sender_TopLevel_SenderSS super;

		public:
			NON_CAN_Sender_TopLevel(){};
			NON_CAN_Sender_TopLevel(const string& name, BaseState* parent, SenderSS* mgr);

			virtual void onMessage(const Mesg& mesg);

			virtual void onEntry();
			virtual void onExit();

		//Transitions

		private:
			void onSERMessage(const Mesg& mesg);
	};

	class ACKNAK_NON_CAN : public virtual NON_CAN_Sender_TopLevel
	{
			typedef NON_CAN_Sender_TopLevel super;

		public:
			ACKNAK_NON_CAN(){};
			ACKNAK_NON_CAN(const string& name, BaseState* parent, SenderSS* mgr);

			virtual void onMessage(const Mesg& mesg);

			virtual void onEntry();
			virtual void onExit();

		//Transitions

		private:
			void onSERMessage(const Mesg& mesg);
	};

	class EOT1_NON_CAN : public virtual NON_CAN_Sender_TopLevel
	{
			typedef NON_CAN_Sender_TopLevel super;

		public:
			EOT1_NON_CAN(){};
			EOT1_NON_CAN(const string& name, BaseState* parent, SenderSS* mgr);

			virtual void onMessage(const Mesg& mesg);

			virtual void onEntry();
			virtual void onExit();

		//Transitions

		private:
			void onSERMessage(const Mesg& mesg);
	};

	class START_NON_CAN : public virtual NON_CAN_Sender_TopLevel
	{
			typedef NON_CAN_Sender_TopLevel super;

		public:
			START_NON_CAN(){};
			START_NON_CAN(const string& name, BaseState* parent, SenderSS* mgr);

			virtual void onMessage(const Mesg& mesg);

			virtual void onEntry();
			virtual void onExit();

		//Transitions

		private:
			void onSERMessage(const Mesg& mesg);
	};

	class EOTEOT_NON_CAN : public virtual NON_CAN_Sender_TopLevel
	{
			typedef NON_CAN_Sender_TopLevel super;

		public:
			EOTEOT_NON_CAN(){};
			EOTEOT_NON_CAN(const string& name, BaseState* parent, SenderSS* mgr);

			virtual void onMessage(const Mesg& mesg);

			virtual void onEntry();
			virtual void onExit();

		//Transitions

		private:
			void onSERMessage(const Mesg& mesg);
	};

	class StatC_NON_CAN : public virtual NON_CAN_Sender_TopLevel
	{
			typedef NON_CAN_Sender_TopLevel super;

		public:
			StatC_NON_CAN(){};
			StatC_NON_CAN(const string& name, BaseState* parent, SenderSS* mgr);

			virtual void onMessage(const Mesg& mesg);

			virtual void onEntry();
			virtual void onExit();

		//Transitions

		private:
			void onSERMessage(const Mesg& mesg);
	};

	class ACKNAKSTAT_NON_CAN : public virtual NON_CAN_Sender_TopLevel
	{
			typedef NON_CAN_Sender_TopLevel super;

		public:
			ACKNAKSTAT_NON_CAN(){};
			ACKNAKSTAT_NON_CAN(const string& name, BaseState* parent, SenderSS* mgr);

			virtual void onMessage(const Mesg& mesg);

			virtual void onEntry();
			virtual void onExit();

		//Transitions

		private:
			void onSERMessage(const Mesg& mesg);
	};

	class CAN_Sender_TopLevel : public virtual Sender_TopLevel_SenderSS
	{
			typedef Sender_TopLevel_SenderSS super;

		public:
			CAN_Sender_TopLevel(){};
			CAN_Sender_TopLevel(const string& name, BaseState* parent, SenderSS* mgr);

			virtual void onMessage(const Mesg& mesg);

			virtual void onEntry();
			virtual void onExit();

		//Transitions

		private:
			void onSERMessage(const Mesg& mesg);
	};

};

#endif

//___________________________________vv^^vv___________________________________
